title:   Elvis Liang
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Motivated and highly skilled analyst with over 4 years of expertise in data science, data engineering, analytics, product experimentation, insight enablement to influence strategic business decisions. Advanced hands-on experiences on using DAX, Power Query, SQL, Power Automate, Python and Gen AI workflows to process, transform and analyze both quantitative and qualitative data. Strong communication, stakeholder management and leadership skills to elicit requirements, comfortable with ambiguity, and able to use rigorous analytical techniques.
  <br>
  <a href="https://www.linkedin.com/in/shuchangl/">View My LinkedIn Profile</a>
  <br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br>
  <a href="https://elvisliang.notion.site/Portfolio-Elvis-Liang-0d7092fc3fc34f50a878f88a380471f6?pvs=4">View My Notion Portfolios</a>
theme: jekyll-theme-minimal   
  
 
